### ISSUE TITLE
It is possible to align records to the left?

### ISSUE THREAD

**Issue by 8ksoft** [imtapps/django-copybook#2]
Hi,

I need to align some records to left when a I make "to_record". If I define a StringField (or any other record field), is there some way to align the output to left instead of right align?

**Comment by imtapps** [comment]
Can you provide a sample of what your code looks like, the result you are getting, and the result you desire? String fields should align to the left (adding spaces to the right as necessary). Int fields should align right (filling in zeros to the left as necessary).

**Comment by 8ksoft** [comment]
Thanks for your response. Sorry, but was a mistake from us. The library djcopybook works fine, we have made a wrong validation of the generated string. I apologize for the generated issue.
